"""complete union relationships

Revision ID: 631d72745ae4
Revises: 45e6e5ad3219
Create Date: 2026-08-15 01:55:01.642927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631d72745ae4'
down_revision: Union[str, Sequence[str], None] = '45e6e5ad3219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_damage', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('raid', sa.Column('union_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'raid', 'unions', ['union_id'], ['id'])
    op.add_column('teams', sa.Column('union_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'unions', ['union_id'], ['id'])
    op.add_column('users', sa.Column('union_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'unions', ['union_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'union_id')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'union_id')
    op.drop_constraint(None, 'raid', type_='foreignkey')
    op.drop_column('raid', 'union_id')
    op.alter_column('mock_damage', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
