"""initial schema

Revision ID: 8ce8698cdb90
Revises: 
Create Date: 2026-08-15 02:14:37.421767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8698cdb90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nikkes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('burst', sa.Integer(), nullable=True),
    sa.Column('element', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('team_order', sa.String(), nullable=True),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attempts_used',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.Column('btn_1', sa.Integer(), nullable=False),
    sa.Column('btn_2', sa.Integer(), nullable=False),
    sa.Column('btn_3', sa.Integer(), nullable=False),
    sa.Column('btn_4', sa.Integer(), nullable=False),
    sa.Column('btn_5', sa.Integer(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raid_id'], ['raid.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weakness', sa.String(), nullable=False),
    sa.Column('hp', sa.BigInteger(), nullable=True),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raid_id'], ['raid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['nikkes.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_done',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_number', sa.BigInteger(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('boss_targeted', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('team_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boss_targeted'], ['boss.id'], ),
    sa.ForeignKeyConstraint(['player'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_used'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_number', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('boss_targeted', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('team_used', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boss_targeted'], ['boss.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_used'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_damage')
    op.drop_table('damage_done')
    op.drop_table('team_characters')
    op.drop_table('boss')
    op.drop_table('attempts_used')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('raid')
    op.drop_table('unions')
    op.drop_table('nikkes')
    # ### end Alembic commands ###
